#region license and copyright
/*
 * The MIT License, Copyright (c) 2011-2025 Marcel Schneider
 * for details see License.txt
 */
#endregion

namespace KataCompiler;

public enum Token
{
    // keep in sync with Punctuation dictionary
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    LeftSquareBracket,
    RightSquareBracket,
    Question,
    Colon,
    Semicolon,
    Comma,
    Point,
    Tilde,
    Asterisk,
    AsteriskEqual,
    Percent,
    PercentEqual,
    Carot,
    CarotEqual,
    Slash,
    SlashEqual,
    Ampersand,
    Ampersand2,
    AmpersandEqual,
    Pipe,
    Pipe2,
    PipeEqual,
    Equal,
    Equal2,
    Equal3,
    Exclamation,
    ExclamationEqual,
    ExclamationEqual2,
    Plus,
    Plus2,
    PlusEqual,
    Minus,
    Minus2,
    MinusEqual,
    LessThan,
    LessThan2,
    LessThanEqual,
    LessThan2Equal,
    GreaterThan,
    GreaterThan2,
    GreaterThanEqual,
    GreaterThan2Equal,
    GreaterThan3,
    GreaterThan3Equal,

    // --- Punctuation dictionary end
    // --- Reserved Keyword
    Break,
    Case,
    Catch,
    Continue,
    Debugger,
    Default,
    Delete,
    Do,
    Else,
    Finally,
    For,
    Function,
    If,
    In,
    Instanceof,
    New,
    Return,
    Switch,
    This,
    Throw,
    Try,
    Typeof,
    Var,
    Void,
    While,
    With,
    True,
    False,
    Null,

    // --- Reserved Keyword end
    WhiteSpace,
    NewLine,
    LineComment,
    BlockComment,
    NumberLiteral,
    StringLiteral,
    Identifier,
    Illegal,
    EOF,
}
